# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'amdUAP' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SSZipArchive'

  # Pods for amdUAP

  target 'amdUAPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'amdUAPUITests' do
    # Pods for testing
  end

end
